services:
  app:
    ports:
      - "127.0.0.1:3001:3000"

  chroma:
    image: chromadb/chroma:latest
    container_name: frieren_chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "127.0.0.1:8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped

volumes:
  chromadb_data: