version: '3.8'

services:
  app:
    build:
      context: . # The directory containing the Dockerfile and your project code
      dockerfile: Dockerfile # The name of the Dockerfile

    container_name: frieren_rag_app

    ports:
      - "127.0.0.1:3001:3000"

    env_file:
      - .env

    depends_on:
      - chroma

    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest 
    container_name: frieren_chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "127.0.0.1:8000:8001" 

    
    volumes:
      - chromadb_data:/chroma/chroma

    restart: unless-stopped

volumes:
  chromadb_data: